### PR TITLE
- switch to boost winapi, to avoid duplicated definitions when compil…

### PR DESCRIPTION
**Pull request by SSE4**
…ing using Clang on Windows

#139

### CODE REVIEW

**Comment by viboes** [comment]
Andrey, could you check this PR using WinApi?

**Comment by Lastique** [comment]
Sorry, @viboes, I didn't receive a notification. I did a quick check and there is an include missing. I'm running the checks again now and will create a PR to this PR to fix it.

**Comment by Lastique** [comment]
Here's the PR with my fixes: https://github.com/SSE4/thread/pull/1.

**Comment by viboes** [comment]
Andrey, if I understand you approve this PR.

**Comment by Lastique** [comment]
My limited testing did not reveal errors and I'm generally in favor of porting to Boost.WinAPI, so you could say so. IMHO, you can merge it rather safely and then watch the test results.

**Comment by viboes** [comment]
I'm confident on your testing.

**Comment by viboes** [comment]
There is an additional issue on Windows that maybe it can be managed by the move to WinAPI.

https://svn.boost.org/trac10/ticket/12323

Please, could you take a look?

**Comment by Lastique** [comment]
That issue is unrelated to the move. AFAICS, that piece of code unconditionally includes windows.h, I see no reason to change that. I'll create a separate PR for that ticket.

**Pull request merged**
